services:
  # nginx
  web:
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8082:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  app:
    build:
      dockerfile: ./php/Dockerfile
      target: app
    volumes:
      - /srv/vendor # Cannot be overwritten
      - ./app:/srv
  db:
    image: mariadb:latest
    volumes:
      - mariadbdata:/var/lib/mysql
    restart: always # replace with always in production
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: nginxphpredis

volumes:
  mariadbdata: ~


  # php
  # mysql
  # redis